services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - srv-pedido-consumer-network
    volumes:
      - rabbitmq-data:/data/rabbit-mq

  srv-pedido-consumer:
    container_name: srv-pedido-consumer
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rabbitmq
      - mongodb-pedido-consumer
    depends_on:
      - rabbitmq
      - mongodb-pedido-consumer
    networks:
      - srv-pedido-consumer-network
    volumes:
      - srv-pedido-consumer-data:/data/pedido-consumer
    environment:
      - RABBITMQ_USERNAME=myuser
      - RABBITMQ_PASS=secret
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - "8081:8081"
    restart: always

  mongodb-pedido-consumer:
    image: mongo:latest
    container_name: mongodb-pedido-consumer
    ports:
      - "27019:27017"
    volumes:
      - mongodb-pedido-consumer-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - srv-pedido-consumer-network

networks:
  srv-pedido-consumer-network:

volumes:
  rabbitmq-data:
  srv-pedido-consumer-data:
  mongodb-pedido-consumer-data:
