spring:
  application:
    name: pedidos
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USERNAME:myuser}
    password: ${RABBITMQ_PASS:secret}
  data:
    mongodb:
      host: mongodb-pedido-consumer
      database: pedido
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpass}
      authentication-database: admin
server:
  port: 8081